title: <p align="center"> Angela Aeschbach </p>
logo: "/images/logo.png?raw=true"
description: >
  <p align="center">
  <a href="mailto: angela.aeschbach@gmail.com"> Email </a> |
  <a href="https://www.linkedin.com/in/aaeschbach/"> LinkedIn </a> |
  <a href="https://github.com/aaeschbach"> GitHub </a>
  </p>

  <p align="justify">
  I recently completed my MSc degree in Bioinformatics and Computational Biology at the University of Bern. 
  <br><br>
  Currently, I am interested in pursuing a career involving data science, data visualization and artificial intelligence; preferably in the field of biological and medical research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
